# Generated by Django 5.2.17 on 2026-09-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_participants", models.PositiveIntegerField()),
                ("max_participants", models.PositiveIntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discount_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tiers", to="campaigns.campaign"
                    ),
                ),
            ],
            options={
                "verbose_name": "Palier de prix",
                "verbose_name_plural": "Paliers de prix",
                "ordering": ["min_participants"],
            },
        ),
    ]
