# Generated by Django 5.2.17 on 2026-09-30 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING_APPROVAL", "En attente d'approbation"),
                            ("ACTIVE", "Active"),
                            ("TARGET_REACHED", "Objectif atteint"),
                            ("PAYMENT_PENDING", "Paiements en attente"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échouée"),
                            ("EXPIRED", "Expirée"),
                            ("CANCELLED", "Annulée"),
                            ("SUSPENDED", "Suspendue"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "pricing_policy",
                    models.CharField(
                        choices=[
                            ("CURRENT_TIER_PRICE", "Prix du palier au moment de l'adhésion"),
                            ("FINAL_TIER_PRICE", "Prix du palier final atteint"),
                        ],
                        default="CURRENT_TIER_PRICE",
                        max_length=30,
                    ),
                ),
                ("target_participants", models.PositiveIntegerField(default=10)),
                ("min_participants", models.PositiveIntegerField(default=2)),
                ("max_participants", models.PositiveIntegerField(blank=True, null=True)),
                ("current_participants_count", models.PositiveIntegerField(default=0)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(db_index=True)),
                ("terms", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="catalog.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne",
                "verbose_name_plural": "Campagnes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="views", to="campaigns.campaign"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("JOINED", "Inscrit"),
                            ("CONFIRMED", "Confirmé"),
                            ("CANCELLED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        db_index=True,
                        default="JOINED",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "JOINED")),
                        fields=("campaign", "user"),
                        name="unique_active_user_participation",
                    )
                ],
            },
        ),
    ]
